# -*- coding: utf-8 -*-
"""Projeto: jogo da adivinhação.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WnmOuahQjbZ983LXgrPtr4rotCqw7gav
"""

import random

numero = random.randint(1, 100)
tentativas = 0 

print("Bem-vindo ao jogo da adivinhação!")
print("Escolha um número de 1 a 100. Você tem 10 tentativas para adivinhar")

while tentativas < 10:
    palpite = int(input("Digite o seu palpite: "))
    tentativas += 1
    
    if palpite == numero:
        print(f"Parabéns, você acertou o número em {tentativas} tentativas")
        break
    elif palpite < numero:
        print("O número é maior. Tente novamente")
    else:
        print("O número é menor. Tente novamente")
else:
    print(f'Você perdeu! O número era {numero}.')